// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7v_7mUMmgvOKmm6hV8IpzKthtIDKAKso',
    appId: '1:225327685629:android:35dade127a822f09ff4394',
    messagingSenderId: '225327685629',
    projectId: 'nood-food-6cee5',
    storageBucket: 'nood-food-6cee5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_dYFLD9OUKgqsb8XQ-tvxh3wOGYaWBmY',
    appId: '1:225327685629:ios:b3420d719961d10aff4394',
    messagingSenderId: '225327685629',
    projectId: 'nood-food-6cee5',
    storageBucket: 'nood-food-6cee5.appspot.com',
    androidClientId: '225327685629-6v86l7cchn7lni0p7fe5e5km3tlmadut.apps.googleusercontent.com',
    iosClientId: '225327685629-5dns7hfc5vo80brt5ahafl5r65m5o6d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
